// Code generated by Slice Machine. DO NOT EDIT.

import BlogPostImage from './BlogPostImage/index.svelte';
import BlogPostContentSection from './BlogPostContentSection/index.svelte';
import BlogPostCodeSnippet from './BlogPostCodeSnippet/index.svelte';
import BlogPostEditNotice from './BlogPostEditNotice/index.svelte';
import PrivacyPolicy from './PrivacyPolicy/index.svelte';

export const components = {
	blog_post_image: BlogPostImage,
	blog_post_section: BlogPostContentSection,
	code_block: BlogPostCodeSnippet,
	edit_notice: BlogPostEditNotice,
	privacy_policy: PrivacyPolicy
};
