// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice = never;

/**
 * Content for About Me documents
 */
interface AboutPageDocumentData {
	/**
	 * Page Content field in *About Me*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.page_content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	page_content: prismic.RichTextField;

	/**
	 * Career field in *About Me*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.career
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	career: prismic.RichTextField;

	/**
	 * Personal field in *About Me*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.personal
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	personal: prismic.RichTextField;

	/**
	 * Slice Zone field in *About Me*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>;
}

/**
 * About Me document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<AboutPageDocumentData>,
	'about_page',
	Lang
>;

/**
 * Primary content in *Blog Post → Slice Zone → Blog Post → Primary*
 */
export interface BlogPostDocumentDataBodyBlogPostSlicePrimary {
	/**
	 * Title field in *Blog Post → Slice Zone → Blog Post → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.body[].blog_post.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * TL;DR field in *Blog Post → Slice Zone → Blog Post → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.body[].blog_post.primary.tldr
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tldr: prismic.KeyTextField;

	/**
	 * Social Media Image field in *Blog Post → Slice Zone → Blog Post → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.body[].blog_post.primary.social_media_image1
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	social_media_image1: prismic.LinkToMediaField;
}

/**
 * Item content in *Blog Post → Slice Zone → Blog Post → Items*
 */
export interface BlogPostDocumentDataBodyBlogPostSliceItem {
	/**
	 * Content field in *Blog Post → Slice Zone → Blog Post → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.body[].blog_post.items.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Slice for *Blog Post → Slice Zone*
 */
export type BlogPostDocumentDataBodyBlogPostSlice = prismic.Slice<
	'blog_post',
	Simplify<BlogPostDocumentDataBodyBlogPostSlicePrimary>,
	Simplify<BlogPostDocumentDataBodyBlogPostSliceItem>
>;

type BlogPostDocumentDataBodySlice =
	| BlogPostDocumentDataBodyBlogPostSlice
	| CodeBlockSlice
	| BlogPostSectionSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * Post Title field in *Blog Post*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.post_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	post_title: prismic.TitleField;

	/**
	 * post_tldr field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Post TL;DR
	 * - **API ID Path**: blog_post.post_tldr
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	post_tldr: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Blog Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.body[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	body: prismic.SliceZone<BlogPostDocumentDataBodySlice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostDocumentData>,
	'blog_post',
	Lang
>;

type HomePageDocumentDataSlicesSlice = RichTextCardSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
	/**
	 * Welcome Message field in *Home Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.welcome_message
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	welcome_message: prismic.RichTextField;

	/**
	 * Slice Zone field in *Home Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomePageDocumentData>,
	'home_page',
	Lang
>;

export type AllDocumentTypes = AboutPageDocument | BlogPostDocument | HomePageDocument;

/**
 * Primary content in *BlogPostSection → Primary*
 */
export interface BlogPostSectionSliceDefaultPrimary {
	/**
	 * Content field in *BlogPostSection → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_section.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for BlogPostSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: BlogPostSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSectionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BlogPostSectionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *BlogPostSection*
 */
type BlogPostSectionSliceVariation = BlogPostSectionSliceDefault;

/**
 * BlogPostSection Shared Slice
 *
 * - **API ID**: `blog_post_section`
 * - **Description**: BlogPostSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostSectionSlice = prismic.SharedSlice<
	'blog_post_section',
	BlogPostSectionSliceVariation
>;

/**
 * Primary content in *CodeBlock → Primary*
 */
export interface CodeBlockSliceDefaultPrimary {
	/**
	 * language field in *CodeBlock → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: shell
	 * - **API ID Path**: code_block.primary.language
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	language: prismic.SelectField<
		'shell' | 'javascript' | 'typescript' | 'powershell' | 'yaml',
		'filled'
	>;

	/**
	 * Code field in *CodeBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: code_block.primary.code
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	code: prismic.RichTextField;
}

/**
 * Default variation for CodeBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: CodeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CodeBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CodeBlock*
 */
type CodeBlockSliceVariation = CodeBlockSliceDefault;

/**
 * CodeBlock Shared Slice
 *
 * - **API ID**: `code_block`
 * - **Description**: CodeBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CodeBlockSlice = prismic.SharedSlice<'code_block', CodeBlockSliceVariation>;

/**
 * Primary content in *RichTextCard → Primary*
 */
export interface RichTextCardSliceDefaultPrimary {
	/**
	 * Message field in *RichTextCard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text_card.primary.message
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	message: prismic.RichTextField;
}

/**
 * Default variation for RichTextCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichTextCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextCardSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextCardSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichTextCard*
 */
type RichTextCardSliceVariation = RichTextCardSliceDefault;

/**
 * RichTextCard Shared Slice
 *
 * - **API ID**: `rich_text_card`
 * - **Description**: RichTextCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextCardSlice = prismic.SharedSlice<'rich_text_card', RichTextCardSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			AboutPageDocument,
			AboutPageDocumentData,
			AboutPageDocumentDataSlicesSlice,
			BlogPostDocument,
			BlogPostDocumentData,
			BlogPostDocumentDataBodyBlogPostSlicePrimary,
			BlogPostDocumentDataBodyBlogPostSliceItem,
			BlogPostDocumentDataBodySlice,
			HomePageDocument,
			HomePageDocumentData,
			HomePageDocumentDataSlicesSlice,
			AllDocumentTypes,
			BlogPostSectionSlice,
			BlogPostSectionSliceDefaultPrimary,
			BlogPostSectionSliceVariation,
			BlogPostSectionSliceDefault,
			CodeBlockSlice,
			CodeBlockSliceDefaultPrimary,
			CodeBlockSliceVariation,
			CodeBlockSliceDefault,
			RichTextCardSlice,
			RichTextCardSliceDefaultPrimary,
			RichTextCardSliceVariation,
			RichTextCardSliceDefault
		};
	}
}
